// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class Admin
{
    public int Id { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public int Identity { get; set; }

    public virtual ICollection<BanGame> BanGames { get; set; } = new List<BanGame>();

    public virtual ICollection<BanMember> BanMembers { get; set; } = new List<BanMember>();
}