// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class BanGame
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int GameId { get; set; }

    public string Content { get; set; }

    public DateTime Date { get; set; }

    public int? AdminId { get; set; }

    public DateTime? StatusTime { get; set; }

    public bool? Status { get; set; }

    public virtual Admin Admin { get; set; }

    public virtual Game Game { get; set; }

    public virtual Member Member { get; set; }
}