// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class BonusProduct
{
    public int Id { get; set; }

    public int ProductTypeId { get; set; }

    public int Price { get; set; }

    public string Url { get; set; }

    public string Name { get; set; }

    public virtual ICollection<BonusItem> BonusItems { get; set; } = new List<BonusItem>();

    public virtual BonusProductType ProductType { get; set; }
}