// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class BonusProductType
{
    public int Id { get; set; }

    public int Type { get; set; }

    public string Name { get; set; }

    public virtual ICollection<BonusProduct> BonusProducts { get; set; } = new List<BonusProduct>();
}