// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class ChatMessage
{
    public int Id { get; set; }

    public int SenderId { get; set; }

    public int ReceiveId { get; set; }

    public string Content { get; set; }

    public DateTime? Time { get; set; }

    public byte? Isread { get; set; }
}