// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class Comment
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int GameId { get; set; }

    public int Rating { get; set; }

    public string Comment1 { get; set; }

    public DateTime? Date { get; set; }

    public virtual ICollection<AttachedComment> AttachedComments { get; set; } = new List<AttachedComment>();

    public virtual Game Game { get; set; }

    public virtual Member Member { get; set; }
}