// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class Developer
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Account { get; set; }

    public string EncryptedPassword { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public DateTime? BanTime { get; set; }

    public bool? IsConfirmed { get; set; }

    public string ConfirmCode { get; set; }

    public virtual ICollection<Discount> Discounts { get; set; } = new List<Discount>();

    public virtual ICollection<Game> Games { get; set; } = new List<Game>();
}