// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class DiscountItem
{
    public int Id { get; set; }

    public int DiscountId { get; set; }

    public int GameId { get; set; }

    public virtual Discount Discount { get; set; }

    public virtual Game Game { get; set; }
}