// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class Dlc
{
    public int Id { get; set; }

    public int DlcId { get; set; }

    public int MainGameId { get; set; }

    public virtual Game DlcNavigation { get; set; }

    public virtual Game MainGame { get; set; }
}