// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class FriendRequest
{
    public int Id { get; set; }

    public int SenderId { get; set; }

    public int ReceiveId { get; set; }

    public virtual Member Receive { get; set; }

    public virtual Member Sender { get; set; }
}