// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class Picture
{
    public int Id { get; set; }

    public string Image { get; set; }

    public int MemberId { get; set; }

    public int BoardId { get; set; }

    public int MessageId { get; set; }

    public virtual Board Board { get; set; }

    public virtual Member Member { get; set; }

    public virtual Message Message { get; set; }
}