// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class TransferPayment
{
    public int Id { get; set; }

    public int TransferMethodsId { get; set; }

    public DateTime PaymentDate { get; set; }

    public decimal PaymentAmount { get; set; }

    public string Info { get; set; }

    public virtual TransferMethod IdNavigation { get; set; }

    public virtual TransferRefund TransferRefund { get; set; }
}