// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class TransferMethod
{
    public int Id { get; set; }

    public string PaymentMethod { get; set; }

    public virtual TransferPayment TransferPayment { get; set; }

    public virtual TransferRefund TransferRefund { get; set; }
}